### ISSUE TITLE
Problem setting up IPs

### ISSUE THREAD

**Issue by guidorugo** [ntrippar/ARPwner#1]
thefatal@vostro:~/ntrippar-ARPwner-42acd7a$ sudo python main.py 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/thefatal/Downloads/Programs/ntrippar-ARPwner-42acd7a/Engine/sniff.py", line 26, in run
    packet = dpkt.ethernet.Ethernet(pkt)
  File "/home/thefatal/Downloads/Programs/ntrippar-ARPwner-42acd7a/Libs/dpkt/dpkt.py", line 72, in __init**
    self.unpack(args[0])
  File "/home/thefatal/Downloads/Programs/ntrippar-ARPwner-42acd7a/Libs/dpkt/ethernet.py", line 100, in unpack
    self.data = self.ip = self._typesw[ETH_TYPE_IP](self.data[3:])
  File "/home/thefatal/Downloads/Programs/ntrippar-ARPwner-42acd7a/Libs/dpkt/dpkt.py", line 72, in __init__
    self.unpack(args[0])
  File "/home/thefatal/Downloads/Programs/ntrippar-ARPwner-42acd7a/Libs/dpkt/ip.py", line 56, in unpack
    raise dpkt.UnpackError, 'invalid header length'
UnpackError: invalid header length

Debian Squeeze, Python 2.6.6

**Comment by ntrippar** [comment]
fixed.
